### ISSUE TITLE
Fatal error: Uncaught ReflectionException: Class Twig_Environment does not exist in 

### ISSUE THREAD

**Issue by arturcesarmelo** [PHP-DI/demo#10]
It worked with other existent classes (controllers, services, etc ...). But even in this repository, `Class Twig_Environment` not exists.

Could anyone help?

**Comment by mnapoli** [comment]
I'm sorry but this isn't a bug. Please direct support to StackOverflow or the chat. I think also you should provide more information so that others help you debug, it might be a problem with your autoloading.
