### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mafio69** [PHP-DI/demo#3]
Fatal error: Uncaught LogicException: You must set a loader first.  HomeController. Help

**Comment by parvinshi** [comment]
`Uncaught LogicException: You must set a loader first. in /usr/local/var/project/php-di-demo/vendor/twig/twig/src/Environment.php:819` 
I also encountered this problem.

**Comment by mafio69** [comment]
It must be changed
use Twig\Environment;
use Twig\Loader\FilesystemLoader;

   Environment::class => function () {
        $loader = new FilesystemLoader(__DIR__ . '/../src/SuperBlog/Views');
        return new Environment($loader);
    };
In file config.php

**Comment by parvinshi** [comment]
> It must be changed
> use Twig\Environment;
> use Twig\Loader\FilesystemLoader;
> 
> Environment::class => function () {
> $loader = new FilesystemLoader(**DIR** . '/../src/SuperBlog/Views');
> return new Environment($loader);
> };
> In file config.php

It's work，thanks

**Comment by solutions2035** [comment]
> It must be changed
> use Twig\Environment;
> use Twig\Loader\FilesystemLoader;
> 
> Environment::class => function () {
> $loader = new FilesystemLoader(**DIR** . '/../src/SuperBlog/Views');
> return new Environment($loader);
> };
> In file config.php

Thank you!

**Comment by vaso123** [comment]
Great. Thank you

**Comment by wirebox-platform** [comment]
Resolved now. All is good with the world. #6

**Comment by wirebox-platform** [comment]
Resolved with #6 
All good :)
